services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_HOST: rabbitmq
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  web:
    restart: always
    build:
      context: .
    env_file:
      - .env
    command: bash -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"

  listener:
    restart: always
    build:
      context: .
    env_file:
      - .env
    command: python consumer.py
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
